### ISSUE TITLE
searching for proteins

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#21]
we should improve search for proteins. 

First, current searching by name appears to be search-when-you-type, which is quite slow to me. Maybe easier to search once user has finished typing and entered the keyword.

Second, search results should be ranked according to increasing edit distance, that is, the number of differences in search term and result. For example, currently when searching for TP53 the first result is TP53AIP1 and the 12th result is TP53. TP53 should occur first, and the next should be a gene where the least amounts of edits are needed (for example TP53I3 - two edits needed).

**Comment by krassowski** [comment]
Search is quite slow right now due to two reasons:
1. per request counting of interactors which allows to show user where there are busy/empty  
2. ongoing imports which are slowing down all operation on server

Both can be resolved: (1) can be precomputed as a column in database, (2) is only temporary issue.

Should I remove "search-when-you-type" mechanism despite that the speed issues are only temporary or wait until those issues will be gone?

PS. ranking is implemented.

**Comment by reimand0** [comment]
Solution of (1) sounds good.

Can we have search-while-type activated after 3rd letter? There will be many hits before that (slow and probably not very useful)

Jüri
