### ISSUE TITLE
showing records in protein search

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#44]
Let's make the search results a little more compact and add some info:

CURRENT VERSION:

TP53

17
+
NM_000546

Coding region: start 7572926 end 7579912 Length: 6986 Transcription positions: start 7571719 end 7590868
protein network (56)

PROPOSED VERSION

TP53
NM_000546 | Protein: 392 residues | CDS: 7572926-7579912 | Transcript: 7571719-7590868 | Chr17 (+) 
VIEWS: Protein sequence (XX PTM sites, YY mutations) | Site-specific PTM interaction network (56 proteins)

**Comment by krassowski** [comment]
Please note, that chromosome number and strand are excluded to upper level because they are gene-wise, not isoform-specific. After clicking "Show more isoforms (n)", the information about chromosome and strand would be repeated (n) times (despite it is always the same) if we move chromosome & strand information to isoform details.

If I made an incorrect assumption about chromosome being gene-specific property please correct (and rebuke) me since it will require database schema change and migrations to change it.

**Comment by reimand0** [comment]
Ok- lets keep strand and Chr on the top layer.

Jüri

**Comment by krassowski** [comment]
Ok. Another small issue:

Currently in brackets after network link, the number displayed is "interactors count". It's defined as: `count(interacting kinases) + count(interacting kinases groups)`. Should I:

- change it to all protein's count [so it will become `count(interacting kinases) + count(kinases associated with interacting kinases groups) `- it's problematic since there are groups with no associated kinases], or
- change label (so instead 'X proteins' use 'X interactors'), or
- leave it as 'X proteins', since it seems plausible to assume that in original studies the _kinease group_ was annotated because an interaction of some protein was detected (but it's not exactly correct when it comes to database content representation).

**Comment by reimand0** [comment]
How about "XX PTM enzymes". Proteins is too general and kinases is
incorrect as we have other enzymes too. Let's not worry about the families
for now.
