### ISSUE TITLE
zero mutation counts at ClinVar view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#47]
https://rl-db.oicr.on.ca/protein/show/NM_002834?filter%5Bsources%5D%5Bcmp%5D=in&filter%5Bsources%5D=ClinVar&filter%5Bis_ptm%5D=None&fallback=True

for example, N18S is cont zero. 

Should we keep or remove these?

**Comment by krassowski** [comment]
The count is zero because there are only non-informative annotations (`not_provided` or `null`) available for this mutation (so they are excluded). But still it's an annotated mutation from ClinVar dataset. I think it might be confusing for user to see a mutation with count 0. Proposed solutions:

1. add second count representing all annotations so it would be `0 (1)` for this mutation,
2. do not show mutations without informative annotations,
3. count all annotations but display only these which are meaningful (so count would be `1`).

To investigate a particular mutation form python-level it is possible to use following script:
```python
from models import Protein, Mutation
protein = Protein.query.filter_by(refseq='NM_002834').one()
mutation = Mutation.query.filter_by(protein_id=protein.id, position=18, alt='S').one()
[c.representation for c in mutation.meta_inherited.clin_data]
```
Which prints out following metadata from ClinVar:
```python
[{'Disease': None,
  'Significane': 'Uncertain significance',
  'Review status': 'single'}]
```

**Comment by reimand0** [comment]
For simplification we should just remove mutations with non-informative
annotations, so selection (2)

**Comment by krassowski** [comment]
It's ready The new test link could be https://rl-db.oicr.on.ca/protein/show/NM_002834?filter%5BMutation.sources%5D=ClinVar&fallback=True. Currently all clinvar mutations without disease name are discarded during import
