### ISSUE TITLE
Last column in mutation table

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#49]
We should update the last column(s) in the mutation table so that they show minimal information. This information will be moved to the record that opens when (+) is clicked.

TCGA:
2 cancer types: GBM, KIRC

ClinVar:
2 disease annotations: Noonan syndrome, Inherited cancer

G1000, ESP6500:
MAF: 0.1234

**Comment by reimand0** [comment]
Regarding cancer type names (long and short), there is a file in dropbox with that information. 

blca	bladder urothelial carcinoma	yellow
brca	breast invasive carcinoma	darkolivegreen2
coadread	colon,rectum adenocarcinoma	cornflowerblue
gbm	glioblastoma multiforme	darkorchid1
hnsc	head and neck squamous cell carcinoma	chartreuse
kirc	kidney renal clear cell carcinoma	burlywood1
laml	acute myeloid leukemia	orange
luad	lung adenocarcinoma	cyan3
lusc	lung squamous cell carcinoma	aquamarine
ov	ovarian serous cystadenocarcinoma	pink
ucec	uterine corpus endometrioid carcinoma	brown1

**Comment by krassowski** [comment]
I have made changes to the file with cancer type names. I adjusted long names of cancers (made some letters uppercase), made short names uppercase and split `coadread colon,rectum adenocarcinoma cornflowerblue` into:
```
COAD Colon adenocarcinoma cornflowerblue
READ Rectum adenocarcinoma cornflowerblue
```
so it now can be seamlessly integrated with the data from TCGA.
That's because parsing TCGA data produced following cancer descriptions:
```python
[<Cancer named: Glioblastoma multiforme>,
 <Cancer named: Ovarian serous cystadenocarcinoma>,
 <Cancer named: Lung adenocarcinoma>,
 <Cancer named: Lung squamous cell carcinoma>,
 <Cancer named: Breast invasive carcinoma>,
 <Cancer named: Kidney renal clear cell carcinoma>,
 <Cancer named: Uterine Corpus Endometrial Carcinoma>,
 <Cancer named: Colon adenocarcinoma>,
 <Cancer named: Acute Myeloid Leukemia>,
 <Cancer named: Rectum adenocarcinoma>,
 <Cancer named: Head and Neck squamous cell carcinoma>,
 <Cancer named: Bladder Urothelial Carcinoma>]
```
which were not matching perfectly to names from file.

Is that all right or should it be done other way round? (i.e. by changing all names from TCGA to lowercase and mapping colon and rectum adenocarcinoma into single unit?)

**Comment by krassowski** [comment]
I found another naming issue. Is `Uterine Corpus Endometrial Carcinoma` the same as `Uterine Corpus Endometrioid Carcinoma`?

**Comment by reimand0** [comment]
OK, this sounds good. Yes, I believe endometrial and endometroid should reflect the same cancer type.
