### ISSUE TITLE
filters for network view

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#72]
we should have the same filters for network view that already exist for protein view - selecting cancer/population/clinvar, cancertype/subpopulation/clinical.signif, PTM sites, etc.

**Comment by krassowski** [comment]
Hi, I would like discuss this issue again. Right know we have kinases colored by number of mutations of given kind which appear in those kinases. We have filters and those filter can reduce this count of mutations. Sometimes the count of mutations is just 0, because there are none. For some reason if a kinase has 0 mutations it is not shown in the network view. I would like to ask if it is desired behaviour or just my mistake/misunderstanding at some point. I can change this quickly to show all kinases (so also those without any mutations) changing one or two lines.

**Comment by reimand0** [comment]
We should show all kinases in these networks, even if they have 0 mutations in some filters. otherwise the network structure will change every time and that can be confusing.
