### ISSUE TITLE
CMS

### ISSUE THREAD

**Issue by reimand0** [reimandlab/Visualisation-Framework-for-Genome-Mutations#79]
Hey - thanks for the CMS, a great start. Couple of quick comments on bugs/issues:
1. clicking on trashcan to remove page - no such page: /remove_page
2. adding a page (Contact) creates a page apparently, but this link is not visible in the frontpage
3. editing does not work either

**Comment by krassowski** [comment]
1 & 3: I see the problem - it affects only the one page where the address was not given. The behaviour of edit and remove function is proper, only the system shouldn't allow to save a page without address (which is like an ID). I will fix that.
2: What behaviour do you expect? (Note: it is possible to add links to front page by editing a page with "/index" address - and it is very perspective way of doing this, because allows great customization and variety of arrangements)

**Comment by reimand0** [comment]
1,3- OK, I understand. i should have given a filename. 

2 - would be best to create an automatic menu on the top where these CMS-generated pages are listed. The CMS could have an additional dropdown field "order" which allows us to specify the rank of each page. In the future we may have either a 2nd menu, or submenus below each primary page.

**Comment by krassowski** [comment]
1,3 - implemented;

2 - Ok, I've got the idea. I will try to tackle both: multiple menus and subentries.

**Comment by krassowski** [comment]
I'm on a good track to have the menus ready for tomorrow (it's mostly in repository, but not deployed to the server yet). It will allow to manage multiple menus and organise them.

**Comment by krassowski** [comment]
So this is finally ready to be reviewed and closed. The footer was recreated as one of menus (so now it can be customised easily) and two more menu slots (top - on a new bar, and side menu) are available. Moreover we have some kind of "settings" -> right now only "brand" name of the website can be set, but we can use it later to store and modify help messages for local "[?]" references.
